version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - api-volume:/app/node_modules
      - .:/app/
    depends_on:
      - db
    networks:
      - balancegame_default
      
    command: nodemon app.js

    stdin_open: true
    tty: true

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: balance_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d  
    networks:
      - balancegame_default

    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  api-volume:

networks:
  balancegame_default:
    external: true