version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - api-volume:/app/node_modules
      - .:/app/
    networks:
      - balancegame_default
    env_file:
      - .env.development.local
      
    command: nodemon app.js

    stdin_open: true
    tty: true

volumes:
  api-volume:

networks:
  balancegame_default:
    external: true